/**
 * @import { ChatInputCommandInteraction, TextChannel } from "discord.js";
 */
const { fetch } = require("undici");
const { SlashCommandBuilder, EmbedBuilder } = require("discord.js");
const { Command } = require.main.require("./commands/internal/class");

const inspirobot_url = "http://inspirobot.me/";
const inspirobot_api_url = "http://inspirobot.me/api?generate=true";
const inspirobot_api_christmas_url = "http://inspirobot.me/api?generate=true&season=xmas";
const inspirobot_icon_url = "https://inspirobot.me/website/images/favicon.png";

module.exports = new Command({
	data: new SlashCommandBuilder()
		.setName("inspire")
		.setDescription("Generates a random inspirational image using inspirobot.me.")
		.addBooleanOption(option =>
			option.setName("christmas")
				.setDescription("Requests a christmas-themed inspirational image.")),
	interaction: async (/** @type ChatInputCommandInteraction */ interaction) => {
		await interaction.deferReply();

		const target_url = interaction.options.getBoolean("christmas", false) ? inspirobot_api_christmas_url : inspirobot_api_url;

		const response = await fetch(target_url);
		if (!response.ok) {
			// Throw error
			await interaction.editReply({
				"embeds": [
					new EmbedBuilder()
						.setAuthor({ "name": "Inspirobot", "url": inspirobot_url, "iconURL": inspirobot_icon_url })
						.setDescription(`An error occured while fetching image.\n${response.status}: ${response.statusText}`),
				],
			});
		}

		// New message
		await interaction.editReply({
			"embeds": [
				new EmbedBuilder()
					.setAuthor({ "name": "Inspirobot", "url": inspirobot_url, "iconURL": inspirobot_icon_url })
					.setImage(await response.text())
					.setFooter({ "text": "Generated by inspirobot.me", "iconURL": interaction.client.user.avatarURL() }),
			],
		});
	}
});
